### ISSUE TITLE
Errors when trying to use an example

### ISSUE THREAD

**Issue by alex4200** [twoolie/NBT#130]
I am trying to use the `block_analysis.py` for a Minecraft world 1.14.3. I have tried two commands

    python block_analysis.py <path_to_world>

and get error

```
Parsing region r.-9.-13.mca...
Traceback (most recent call last):
  File "block_analysis.py", line 149, in <module>
    sys.exit(main(world_folder, start, stop))
  File "block_analysis.py", line 120, in main
    process_region_file(region, start, stop)
  File "block_analysis.py", line 78, in process_region_file
    for c in region.iter_chunks_class():
  File "/Users/mc/Code/NBT/nbt/region.py", line 494, in iter_chunks_class
    yield self.chunkclass(self.get_chunk(m.x, m.z))
  File "/Users/mc/Code/NBT/nbt/chunk.py", line 255, in __init__
    raise NotImplemented
TypeError: exceptions must derive from BaseException
```

and also 

    python block_analysis.py <path_to_world>/region

with error 
```
```
Traceback (most recent call last):
  File "block_analysis.py", line 149, in <module>
    sys.exit(main(world_folder, start, stop))
  File "block_analysis.py", line 116, in main
    world = WorldFolder(world_folder)
  File "/Users/mc/Code/NBT/nbt/world.py", line 259, in __call__
    raise UnknownWorldFormat("Empty world or unknown format")
nbt.world.UnknownWorldFormat: Empty world or unknown format
```


I am doing something wrong? How can I fix this error?

**Comment by AdamBlance** [comment]
This is because you're trying to use it with a 1.14.3 world. Looks like AnvilChunk only supports 1.13.2 worlds at the moment.
